# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://lincolnmullen.com
title: Lincoln Mullen
name: Lincoln Mullen
author: Lincoln Mullen
tagline: Historian of American religions

# RSS / Email 
subscribe_rss: http://feeds.feedburner.com/LincolnMullenWritings
subscribe_rss: http://lincolnmullen.com/atom.xml
# subscribe_email: http://feedburner.google.com/fb/a/mailverify?uri=LincolnMullenWritings&amp;loc=en_US
# RSS feeds can list your email address if you like
email: lincoln@lincolnmullen.com

root: /
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
gems: [jekyll_figure]
markdown: pandoc
pandoc:
  extensions:
    - smart
figures:
  dir: /figures
  enumerate: true
  analytics: true
lsi: false
pygments: false

# Google Analytics
google_analytics_tracking_id: UA-25121492-1

