auto: false
base-url: http://lincolnmullen.com
baseurl: http://lincolnmullen.com
destination: ./_site
exclude: imports/, Rakefile
server: false
server_port: 4000
source: .
url: http://lincolnmullen.com/
