# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://lincolnmullen.com
title: Lincoln Mullen
name: Lincoln Mullen
author: Lincoln Mullen

limit_posts: 1

# RSS / Email 
subscribe_rss: http://lincolnmullen.com/atom.xml
email: lincoln@lincolnmullen.com

root: /
permalink: /blog/:title/
source: source
destination: public
plugins_dir: plugins
gems: 
  - jekyll_figure
  - jekyll-pandoc
  - jekyll-paginate
excerpt_separator: <!--more-->
markdown: pandoc
pandoc:
  extensions:
    - smart
figures:
  dir: /figures
  enumerate: true
  analytics: true
lsi: false
# highlighter: false
collections:
- projects
- software
paginate: 10
paginate_path: "/blog/page/:num/"

# Google Analytics
google_analytics_tracking_id: UA-25121492-1

