# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://lincolnmullen.com
title: Lincoln Mullen
name: Lincoln Mullen
author: Lincoln Mullen
description: American religious history in prose and code

# RSS / Email 
subscribe_rss: http://feeds.feedburner.com/LincolnMullenWritings
subscribe_email: http://feedburner.google.com/fb/a/mailverify?uri=LincolnMullenWritings&amp;loc=en_US
# RSS feeds can list your email address if you like
email: lincoln@lincolnmullen.com

root: /
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
markdown: pandoc
pandoc:
  extensions:
    - smart
lsi: false
pygments: true

# Google Analytics
google_analytics_tracking_id: UA-25121492-1

