# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://lincolnmullen.com
title: Lincoln Mullen
name: Lincoln Mullen
author: Lincoln Mullen
tagline: Historian of American religions

# RSS / Email 
subscribe_rss: http://lincolnmullen.com/atom.xml
email: lincoln@lincolnmullen.com

root: /
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
gems: [jekyll_figure]
# excerpt_separator: <!--more-->
markdown: pandoc
pandoc:
  extensions:
    - smart
figures:
  dir: /figures
  enumerate: true
  analytics: true
lsi: false
highlighter: false
paginate: 8
# paginate_path: "blog/page:num"

# Google Analytics
google_analytics_tracking_id: UA-25121492-1

