# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://lincolnmullen.com
title: Lincoln A. Mullen
name: Lincoln A. Mullen
author: Lincoln A. Mullen
description: Lincoln A. Mullen is a historian of American religion and a PhD candidate at Brandeis University.

# RSS / Email 
subscribe_rss: http://feeds.feedburner.com/LincolnMullenWritings
subscribe_email: http://feedburner.google.com/fb/a/mailverify?uri=LincolnMullenWritings&amp;loc=en_US
# RSS feeds can list your email address if you like
email: lincoln@lincolnmullen.com

root: /
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
markdown: pandoc
pandoc:
  extensions:
    - smart

pygments: true

# Google Analytics
google_analytics_tracking_id: UA-25121492-1
